---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys the 3decision helm chart, as well as related helm and kubernetes resources. (qs-1snm79fel)."
Metadata:
  cfn-lint: { config: { ignore_checks: [ E3001 ] } }
  LintSpellExclude:
    - Discngine
    - 3decision
Parameters:
  TNamespace:
    Default: tdecision
    Type: String
  JWTPrivateKey:
    Type: String
    NoEcho: true
  JWTPublicKey:
    Type: String
  EKSClusterName:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBConnectionString:
    Type: String
  DataPubVolumeID:
    Type: String
  DomainName:
    Type: String
  CertificateArn:
    Type: String
  HostString:
    Type: String
  DBName:
    Type: String
  LoadBalancerType:
    Type: String
  AzureClientId:
    Type: String
  AzureTenant: 
    Type: String
  AzureSecret: 
    Type: String
  AzureRedirectUri:
    Type: String
  OktaClientId:
    Type: String
  OktaSecret:
    Type: String
  OktaDomain:
    Type: String
  OktaServerId:
    Type: String
  OktaRedirectUri:
    Type: String
  MainSubdomain:
    Type: String
  ApiSubdomain:
    Type: String
  HelpSubdomain:
    Type: String
  LoadBalancerClass:
    Type: String

Conditions:
  AzureUnused: !Equals [!Ref AzureClientId, ""]
  OktaUnused: !Equals [!Ref OktaClientId, ""]
  NginxLB: !Equals [!Ref LoadBalancerClass, "nginx"]

Resources:
  EncryptedStorageClass:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: 'default'
      Manifest: !Sub |
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: gp2-encrypted
        parameters:
          fsType: ext4
          type: gp2
          encrypted: "true"
        provisioner: kubernetes.io/aws-ebs
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
  TDecisionNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    DeletionPolicy: Retain
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: 'kube-system'
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${TNamespace}
  RabbitMQChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    DependsOn: EncryptedStorageClass
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: rabbitmq
      Namespace: rabbitmq
      Repository: https://charts.bitnami.com/bitnami
      Chart: rabbitmq
      Version: 6.27.1
      Values:
        image.tag: 3.8.19-debian-10-r30
        rabbitmq.username: discngine
        rabbitmq.password: lapin79
        global.storageClass: gp2-encrypted
  CertManager:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: cert-manager
      Namespace: cert-manager
      Repository: https://charts.jetstack.io
      Chart: cert-manager
      Version: 1.8.0
      Values:
        installCRDs: true
  IngressNginx:
    Type: "AWSQS::Kubernetes::Helm"
    Condition: NginxLB
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: ingress-nginx
      Namespace: ingress-nginx
      Repository: https://kubernetes.github.io/ingress-nginx
      Chart: ingress-nginx
  RedisChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    DependsOn: EncryptedStorageClass
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: sentinel
      Namespace: redis-cluster
      Chart: oci://fra.ocir.io/discngine1/3decision_kube/redis-sentinel:16.3.1
      Values:
        global.storageClass: gp2-encrypted
  JWTSecret:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: TDecisionNamespace
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !Ref TNamespace
      Manifest: !Sub |
        kind: Secret
        apiVersion: v1
        type: opaque
        metadata:
          name: 3decision-jwt-secret
          namespace: ${TNamespace}
        data:
          id_rsa: ${JWTPrivateKey}
          id_rsa.pub: ${JWTPublicKey}
  ChangeDBPass:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: TDecisionNamespace
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !Ref TNamespace
      Manifest: !Sub |
        kind: Pod
        apiVersion: v1
        metadata:
          name: db-pass-change
        spec:
          restartPolicy: OnFailure
          containers:
          - name: db-pass-change
            image: fra.ocir.io/discngine1/3decision_kube/sqlcl
            command: ["/bin/bash", "-c"]
            args:
            - echo -ne '
              alter user ADMIN identified by "${DBPassword}";
              alter user PD_T1_DNG_THREEDECISION identified by "${DBPassword}" ACCOUNT UNLOCK;
              alter user PD_T1_DNG_CORE identified by "${DBPassword}" ACCOUNT UNLOCK;
              alter user CHEMBL_29 identified by "${DBPassword}" ACCOUNT UNLOCK;' > changepwd.sql;
              /root/sqlcl/bin/sql admin/Ch4ng3m3f0rs3cur3p4ss@${DBConnectionString} @changepwd.sql
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
              requests:
                cpu: 150m
                memory: 250Mi
  TdecisionChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: [ TDecisionNamespace, JWTSecret, RabbitMQChart, EncryptedStorageClass ]
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: tdecision
      Namespace: !Ref TNamespace
      Chart: oci://fra.ocir.io/discngine1/3decision_kube/3decision-helm:1.0.1
      Values:
        nodeCloud.volumes.jwtSecret.name: 3decision-jwt-secret
        oracle.password: !Ref DBPassword
        oracle.connectionString: !Ref DBConnectionString
        oracle.hostString: !Ref HostString
        oracle.pdbString: !Ref DBName
        oracle.choral.password: !Ref DBPassword
        volumes.storageClassName: gp2-encrypted
        wikijs.pvc.storageClassName: gp2-encrypted
        volumes.claimPods.backend.publicdata.awsElasticBlockStore.fsType: ext4
        volumes.claimPods.backend.publicdata.awsElasticBlockStore.volumeID: !Ref DataPubVolumeID
        volumes.claimPods.backend.publicdata.awsElasticBlockStore.availabilityZone: !Select [ 0, Fn::GetAZs: !Ref 'AWS::Region' ]
        ingress.host: !Ref DomainName
        ingress.certificateArn: !Ref CertificateArn
        ingress.visibility: !Ref LoadBalancerType
        nest.env.internal_api_key.value: !Select [2, !Split ['/', !Ref AWS::StackId]]
        ingress.class: !Ref LoadBalancerClass
        nest.env.azure_tenant.value: !Ref AzureTenant
        nest.env.azure_client_id.value: !If [ AzureUnused, "none", !Ref AzureClientId ]
        nest.env.azure_secret.value: !Ref AzureSecret
        nest.env.azure_redirect_uri.value: !Ref AzureRedirectUri
        nest.env.okta_domain.value: !Ref OktaDomain
        nest.env.okta_server_id.value: !Ref OktaServerId
        nest.env.okta_client_id.value: !If [ OktaUnused, "none", !Ref OktaClientId ]
        nest.env.okta_secret.value: !Ref OktaSecret
        nest.env.okta_redirect_uri.value: !Ref OktaRedirectUri
        ingress.ui.host: !Ref MainSubdomain
        ingress.api.host: !Ref ApiSubdomain
        ingress.wikijs.host: !Ref HelpSubdomain
  ChoralChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: choral
      Namespace: choral
      Chart: oci://fra.ocir.io/discngine1/3decision_kube/choral-helm:1.0.0
      Values:
        oracle.password: !Ref DBPassword
        oracle.connectionString: !Ref DBConnectionString
        pvc.storageClassName: gp2-encrypted
  CreateIndexes:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: ChoralChart
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: choral
      Manifest: !Sub |
        kind: Pod
        apiVersion: v1
        metadata:
          name: index-change
        spec:
          restartPolicy: OnFailure
          containers:
          - name: index-change
            image: fra.ocir.io/discngine1/3decision_kube/sqlcl
            command: ["/bin/bash", "-c"]
            args:
            - sleep 5m;
              echo -ne '
              WHENEVER SQLERROR EXIT SQL.SQLCODE;\n
              CREATE INDEX IDX_CHOR_STR_SMALL_MOL_SMILES ON STRUCTURE_SMALL_MOL(SMILES) INDEXTYPE IS CHORAL_OWNER.STRICT_IDXTYPE;\n
              CREATE INDEX IDX_CHOR_TAU_SMALL_MOL_SMILES ON STRUCTURE_SMALL_MOL(SMILES) INDEXTYPE IS CHORAL_OWNER.TAUTOMER_IDXTYPE;\n
              CREATE INDEX IDX_CHOR_TAUISO_SMS ON STRUCTURE_SMALL_MOL(SMILES) INDEXTYPE IS CHORAL_OWNER.TAUTOMER_ISOMER_IDXTYPE;\n
              CREATE INDEX IDX_CHOR_STRISO_SMS ON STRUCTURE_SMALL_MOL(SMILES) INDEXTYPE IS CHORAL_OWNER.STRICT_ISOMER_IDXTYPE;\n' > pd_t1_index.sql;
              exit | /root/sqlcl/bin/sql PD_T1_DNG_THREEDECISION/${DBPassword}@${DBConnectionString} @pd_t1_index.sql;
              ret=$?;
              if [ $ret -ne 0 ]; then
                echo -ne '
                DROP INDEX IDX_CHOR_STR_SMALL_MOL_SMILES;\n
                DROP INDEX IDX_CHOR_TAU_SMALL_MOL_SMILES;\n
                DROP INDEX IDX_CHOR_TAUISO_SMS;\n
                DROP INDEX IDX_CHOR_STRISO_SMS;\n' > delete_pd_t1_index.sql;
                exit | /root/sqlcl/bin/sql PD_T1_DNG_THREEDECISION/${DBPassword}@${DBConnectionString} @delete_pd_t1_index.sql;        
              exit 1;
              fi;
              echo -ne '
              WHENEVER SQLERROR EXIT SQL.SQLCODE;\n
              CREATE INDEX IDX_CHOR_STR_CMP_STRUC ON COMPOUND_STRUCTURES(CANONICAL_SMILES) INDEXTYPE IS CHORAL_OWNER.STRICT_IDXTYPE;\n
              CREATE INDEX IDX_CHOR_TAU_CMP_STRUC ON COMPOUND_STRUCTURES(CANONICAL_SMILES) INDEXTYPE IS CHORAL_OWNER.TAUTOMER_IDXTYPE;\n
              CREATE INDEX IDX_CHOR_TAUISO_CMP_STRUC ON COMPOUND_STRUCTURES(CANONICAL_SMILES) INDEXTYPE IS CHORAL_OWNER.TAUTOMER_ISOMER_IDXTYPE;\n
              CREATE INDEX IDX_CHOR_STRICT_CMP_STRUC ON COMPOUND_STRUCTURES(CANONICAL_SMILES) INDEXTYPE IS CHORAL_OWNER.STRICT_ISOMER_IDXTYPE;\n' > chembl_29_index.sql;
              exit | /root/sqlcl/bin/sql CHEMBL_29/${DBPassword}@${DBConnectionString} @chembl_29_index.sql;
              ret=$?;
              if [ $ret -ne 0 ]; then
                echo -ne '
                DROP INDEX IDX_CHOR_STR_CMP_STRUC;\n
                DROP INDEX IDX_CHOR_TAU_CMP_STRUC;\n
                DROP INDEX IDX_CHOR_TAUISO_CMP_STRUC;\n
                DROP INDEX IDX_CHOR_STRICT_CMP_STRUC;\n' > delete_chembl_29_index.sql;
                exit | /root/sqlcl/bin/sql CHEMBL_29/${DBPassword}@${DBConnectionString} @delete_chembl_29_index.sql;        
                exit 1;
              fi;
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
              requests:
                cpu: 150m
                memory: 250Mi