---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys a Volume based on a public snapshot (qs-1snm79fe6)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "3decision EBS volume creation"
  LintSpellExclude:
    - Discngine
    - 3decision
Mappings: 
  RegionMap: 
    us-east-1:
      DataPub: snap-061bd58995aaeb78a
    eu-central-1:
      DataPub: snap-0ab16ade3a8e61ec5
Resources:
  DataPub:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      SnapshotId: !FindInMap [RegionMap, !Ref "AWS::Region", DataPub]
      Encrypted: false
Outputs:
  DataPubVolumeID:
    Description: ID of the collection volume
    Value: !Ref DataPub