---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys A records in a given route53 hosted zone (qs-1snm79fdq)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "3decision Route53 DNS creation"
  LintSpellExclude:
    - Discngine
    - 3decision
Parameters:
  HostedZoneId:
    Type: String
  DomainName:
    Type: String
Mappings:
  Config:
    Prefix: { Value: 'eks-quickstart' }
Resources:
  DNSName:
    Type: Custom::CliQuery
    Properties:
      ServiceToken: !Sub ['arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-ResourceReader', {Prefix: !FindInMap [Config, Prefix, Value]}]
      AwsCliCommand: "elbv2 describe-load-balancers --names lb-3dec --query 'LoadBalancers[0].{DNSName: DNSName}'"
      IdField: 'DNSName'
  CanonicalHostedZoneId:
    Type: Custom::CliQuery
    Properties:
      ServiceToken: !Sub ['arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-ResourceReader', {Prefix: !FindInMap [Config, Prefix, Value]}]
      AwsCliCommand: "elbv2 describe-load-balancers --names lb-3dec --query 'LoadBalancers[0].{CanonicalHostedZoneId: CanonicalHostedZoneId}'"
      IdField: 'CanonicalHostedZoneId'
  tdecRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "3decision.${DomainName}"
      Type: A
  apiRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "api.3decision.${DomainName}"
      Type: A
  wikiRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "3decision-help.${DomainName}"
      Type: A
  backRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "3decision-debug.${DomainName}"
      Type: A